### ISSUE TITLE
Practical plants default values should be restrictive/null

### ISSUE THREAD

**Issue by JustTB** [Ecohackerfarm/powerplant#27]
At the moment the default values in practicalplants.js are imho wrong since they lead to wrong information and wrong match making.

I think the default values should be null or empty arrays depending on the format.

**Comment by petteripitkanen** [comment]
Yep, defaults (other than nulls or empty arrays) should not be chosen at the data normalization level.

Currently the defaults are chosen for the companionship algorithm to be optimistic when data is missing. If such optimistic behavior is wanted it should be implemented on the level of the companionship algorithm (shared/companionship.js).
