### ISSUE TITLE
Add descriptions to plant attributes from practicalplants

### ISSUE THREAD

**Issue by ScottA38** [Ecohackerfarm/powerplant#32]
New plant/crop attributes are to be added to the practical plants database (data model).

For the accurate documentation of the expanded data model these attributes should integrated into the source codes's JSDoc knowledge base.

The attributes to be documented can be found at <repository root>/server/models/crops.js where the JSDoc attributes will be clear as some already have defined descriptions and some do not

**Comment by petteripitkanen** [comment]
Specification for this has changed somewhat as the crop database (and everything else) has been moved from MongoDB to PouchDB. Challenge is to find a good place to document these, maybe in `db/practicalplants.js` somewhere near the constant `PP_MAPPINGS` would be the clearest for now.

**Comment by petteripitkanen** [comment]
Added documentation for the `Crop` object type in #61.
