### ISSUE TITLE
Move complex data calculations to client side

### ISSUE THREAD

**Issue by JustTB** [Ecohackerfarm/powerplant#6]
Expensive calculations should be done on the client side to release the server from processing.

Move/implement complex functions from server to client:
- `getCompatibleCrops`
- `getCropGroups`
- `removeCropGroupsFromCombinations`
- check for other complex calculations you find on the server side e. g. `server/processor.js` that should be moved

**Comment by petteripitkanen** [comment]
Done by #38.
