### ISSUE TITLE
Test that values of name properties start with upper case letter

### ISSUE THREAD

**Issue by petteripitkanen** [Ecohackerfarm/powerplant#78]
This is quite clear for _family_ and _genus_, but _commonName_ and _binomialName_ are not so clear. Add the test to `test/db/practicalplants.js`.

**Comment by l0n3star** [comment]
@petteripitkanen I'd like to take this one

**Comment by petteripitkanen** [comment]
You can open a PR.

**Comment by l0n3star** [comment]
@petteripitkanen I just submitted a PR.
