### ISSUE TITLE
Fix practicalplants name properties to start with upper case letter

### ISSUE THREAD

**Issue by petteripitkanen** [Ecohackerfarm/powerplant#87]
With #86 it was found that there are some name properties in `practicalplants.json` that don't start with an upper case letter. The conversion should happen in `readCrops` by calling `replaceValue` for each erroneous case.

**Comment by l0n3star** [comment]
@petteripitkanen I'll take this one.

**Comment by l0n3star** [comment]
PR submitted

**Comment by petteripitkanen** [comment]
Fixed by #88.
